language: ruby
install:
 - jdk_switcher use oraclejdk7
 # Warning: Setting DYLD_* vars can break dynamic linking.
 - unset DYLD_LIBRARY_PATH
 # Warning: You have a non-Homebrew 'pkg-config' in your PATH
 - sudo rm -f /usr/bin/pkg-config
 # Warning: "config" scripts exist outside your system or Homebrew directories.
 - sudo rm -f /usr/local/clang-3.4/bin/llvm-config

 # Install gcc-4.9 system wide[Default is gcc-4.6]
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y > /dev/null
 - sudo apt-get update -qq > /dev/null
 - sudo apt-get install -y libyajl-dev libxml2-dev libxqilla-dev > /dev/null
 - sudo apt-get install -y libstdc++-4.9-dev > /dev/null
 - sudo apt-get install -y g++-4.9 gfortran-4.9 > /dev/null
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90 > /dev/null
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90 > /dev/null
 - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-4.9 90 > /dev/null

 # Install BLAS, LAPACK
 - sudo apt-get install -y libblas-dev liblapack-dev > /dev/null
 # Install openmpi
 - sudo apt-get install openmpi-bin > /dev/null

 - cd ..
 - git clone https://github.com/Homebrew/linuxbrew.git
 - PATH=$PWD/linuxbrew/bin:$PATH
 - LD_LIBRARY_PATH=$PWD/linuxbrew/lib:$LD_LIBRARY_PATH

  # Symlink gcc, gfortran
 - ln -s $(which gcc) $PWD/linuxbrew/bin/gcc-$(gcc -dumpversion |cut -d. -f1,2)
 - ln -s $(which g++) $PWD/linuxbrew/bin/g++-$(g++ -dumpversion |cut -d. -f1,2)
 - ln -s $(which gfortran) $PWD/linuxbrew/bin/gfortran-$(gfortran -dumpversion |cut -d. -f1,2)

 # Install pkg-config[See: https://github.com/Homebrew/homebrew-science/pull/1664#issuecomment-69259072]
 - brew install pkg-config

 - mkdir -p linuxbrew/Library/Taps/homebrew

 # Tap homebrew/python
 - brew tap homebrew/python

 - mv homebrew-science linuxbrew/Library/Taps/homebrew/
 - cd linuxbrew/Library/Taps/homebrew/homebrew-science
 - brew tap --repair

 # Incorrect file permissions: chmod 644
 - chmod 644 *.rb
script:
 - bash travisCI/travis.sh
notifications:
 email: false
