language: ruby
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: xcode7.3
      rvm: system
    - os: linux
      rvm: system
      services: docker
      sudo: required
  allow_failures:
    - os: linux

before_install:
  - if [ -f ".git/shallow" ]; then
      travis_retry git fetch --unshallow;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      sudo chown -R "$USER" "$(brew --repo)";
      git -C "$(brew --repo)" reset --hard origin/master;
      git -C "$(brew --repo)" clean -qxdff;
      brew update || brew update;
      mkdir -p "$(brew --repo)/Library/Taps/homebrew";
      ln -s "$TRAVIS_BUILD_DIR" "$(brew --repo)/Library/Taps/homebrew/homebrew-science";
      cd "$(brew --repo)/Library/Taps/homebrew/homebrew-science";
      export TRAVIS_BUILD_DIR="$(brew --repo)/Library/Taps/homebrew/homebrew-science";
    fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      docker pull linuxbrew/linuxbrew;
      docker run
        -v $(pwd):/home/linuxbrew/homebrew-science
        linuxbrew/linuxbrew
        /bin/sh -c 'brew tap homebrew/python && brew update && cp -rf ~/homebrew-science $(brew --repo)/Library/Taps/homebrew/homebrew-science';
      docker commit $(docker ps -l -q) linuxbrew;
    fi
  - env | grep TRAVIS | tee /tmp/travis.env

install:
  - export HOMEBREW_DEVELOPER="1"
  - ulimit -n 1024

script:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew test-bot --tap=homebrew/science;
    else
      docker run
        -w /home/linuxbrew/.linuxbrew/Library/Taps/homebrew/homebrew-science
        --env-file /tmp/travis.env
        -e HOMEBREW_DEVELOPER=1
        -t
        linuxbrew
        brew test-bot --tap=homebrew/science;
    fi

notifications:
  email:
    on_success: never
    on_failure: always
