language: ruby
rvm: system
sudo: required
services: docker
os: linux

matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system
    - env: OSX=10.10
      os: osx
      osx_image: xcode7
      rvm: system
    - env: OSX=10.9
      os: osx
      osx_image: beta-xcode6.2
      rvm: system

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      sudo chown -R $USER $(brew --repo);
      brew tap homebrew/python;
      brew update;
      ln -s $PWD $(brew --repo)/Library/Taps/homebrew/homebrew-science;
      cd $(brew --repo)/Library/Taps/homebrew/homebrew-science;
      export TRAVIS_BUILD_DIR="$(brew --repo)/Library/Taps/homebrew/homebrew-science";
    fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      docker pull sjackman/linuxbrew-standalone;
      docker run
        -v $(pwd):/home/linuxbrew/homebrew-science
        sjackman/linuxbrew-standalone
        /bin/sh -c 'brew tap homebrew/python && brew update && cp -rf ~/homebrew-science $(brew --repo)/Library/Taps/homebrew/homebrew-science';
      docker commit $(docker ps -l -q) linuxbrew;
    fi
  - env | grep TRAVIS | tee /tmp/travis.env

script:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew test-bot --tap=homebrew/science;
    else
      docker run
        -w /home/linuxbrew/.linuxbrew/Library/Taps/homebrew/homebrew-science
        --env-file /tmp/travis.env
        -t
        linuxbrew
        brew test-bot --tap=homebrew/science;
    fi

notifications:
  email: false
